### ISSUE TITLE
Permission is wrong

### ISSUE THREAD

**Issue by ryanjm** [atmoz/tarsnap#1]
When I try to run this container I'm getting:

```
tarsnap: fopen(/tarsnap/key): Permission denied
tarsnap: Cannot read key file: /tarsnap/key
```

How do you ensure that user `tarsnap` has permission to read the attached files?

**Comment by atmoz** [comment]
Sorry about that. I got lucky when I made this, the tarsnap user created accidentally had the same UID as my host user. That's why it worked when I tested it. But of course, other hosts don't necessary have the same UID. I thought it would be more secure, but in retrospect, it doesn't really matter, as tarsnap is installed as root anyway.

I have updated the install procedure to also validate the tarball with sha256 (5675ed2587bbe48ce4ee1d967b729b44b174d60b).
